print ('Please enter the following information: \n')
first_name = input ('First name: ').capitalize()
last_name = input ('Last name: ').upper()
email = input ('Email Address: ').lower()
phone = input ('Phone Number: ')
job_title = input ('Job Title: ').capitalize()
id_no = input ('ID Number: ')
hair_color = input ('Hair color: ').capitalize()
eye_color = input ('Eye color: ').capitalize()
month_started = input ('Month start: ').capitalize()
training = input ('Completed training: ').capitalize()

print (f'\nThe ID Card is: ')
print (f'----------------------------------------')
print (f'{last_name}, {first_name}')
print (f'{job_title}')
print (f'ID: {id_no} \n')

print (f'{email}')
print (f'{phone} \n')

print (f'Hair: {hair_color:10} Eyes:{eye_color}')
print (f'Month: {month_started:9} Training:{training}')
print (f'----------------------------------------')
